# Generated by Django 4.2.5 on 2023-10-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')
                 ),
                ('email', models.EmailField(
                    max_length=254,
                    unique=True,
                    verbose_name='email')
                 ),
                ('fullname', models.CharField(
                    max_length=255,
                    verbose_name='ФИО')
                 ),
                ('comment', models.TextField(
                    blank=True,
                    null=True,
                    verbose_name='Комментарий')
                 ),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')
                 ),
                ('timestamp', models.DateTimeField(
                    auto_now_add=True,
                    verbose_name='Дата и время последней попытки')
                 ),
                ('status', models.CharField(
                    max_length=20,
                    verbose_name='Статус попытки')
                 ),
                ('response', models.TextField(
                    blank=True,
                    verbose_name='Ответ сервера')
                 ),
            ],
        ),
        migrations.CreateModel(
            name='MailingSettings',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('start_date', models.DateTimeField(
                    verbose_name='Начало рассылки')
                 ),
                (
                    'end_date',
                    models.DateTimeField(verbose_name='Окончание рассылки')
                ),
                ('periodicity', models.CharField(
                    choices=[
                        ('daily', 'Ежедневно'),
                        ('weekly', 'Еженедельно'),
                        ('monthly', 'Ежемесячно')
                    ],
                    max_length=10,
                    verbose_name='Периодичность')
                 ),
                ('status', models.CharField(
                    choices=[
                        ('created', 'Created'),
                        ('started', 'Started'),
                        ('completed', 'Completed')
                    ],
                    default='created',
                    max_length=10,
                    verbose_name='Статус')
                 ),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')
                 ),
                ('subject', models.CharField(verbose_name='Тема')),
                ('content', models.TextField(verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
    ]
