# Generated by Django 4.2.5 on 2023-10-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_mailingsettings_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Тема'),
        ),
    ]
